lastupdatecheck: 0
recentrepos:
- /home/kate/hackathon-project
- /home/kate/catppuccin/catppuccin-waybar
- /home/kate/Bento
- /home/kate/catppuccin/catppuccin-hyprland
- /home/kate/zeppelin-language-server
- /home/kate/lspdiags.nvim
- /home/kate/zeppelin.nvim
- /home/kate/Zeppelin
- /home/kate/.config/nvim/lua/diag
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
